#!/usr/bin/env bash
#MISE description="Start the Docker containers for development using docker compose."
set -e

# Automatically export all variables defined in the .env file to the shell
set -a
source .env
set +a

docker compose up -d database redis